require("dvie.packer")
require("dvie.core.remaps")

require("dvie.plugins.harpoon")

require("dvie.core.options")
require("dvie.core.colorscheme")
require("dvie.plugins.comment")
require("dvie.plugins.nvim-tree")
require("dvie.plugins.lualine")
require("dvie.plugins.telescope")
require("dvie.plugins.nvim-cmp")
require("dvie.plugins.lsp.mason")
require("dvie.plugins.lsp.lspsaga")
require("dvie.plugins.lsp.lspconfig")
require("dvie.plugins.lsp.null-ls")
require("dvie.plugins.autopairs")
require("dvie.plugins.treesitter")
require("dvie.plugins.gitsigns")
